spring.application.name=BasicAuth
db.url=jdbc:mysql://localhost:3306/Hospital?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
db.username=root
db.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


